### ISSUE TITLE
dataGrid is Empty, Please Check it again!!!

### ISSUE THREAD

**Issue by darnkez** [T5ive/Tools-Injector-Mod-Menu#5]
this message is pop up every time i want to add a function, bcs that i cant add any new function (version 1.4.2)

**Comment by T5ive** [comment]
Please specify more details. 
What function did you add? 
Please print screen

**Comment by darnkez** [comment]
i have no problem when add Category function, but when i want to add all hook or patch function, its showing dataGrid is Empty, Please Check it again!!!

**Comment by darnkez** [comment]
like this https://ibb.co/hfbJ3P1

**Comment by T5ive** [comment]
Are you serious?
Because you didn't add anything to the table.
Right click on an empty table -> select 'Add'
![ภาพ](https://user-images.githubusercontent.com/41800233/129356931-4017fcce-5da2-4716-acc4-4ee41f9cb6a9.png)

or try load this file for example
[Test-app.zip](https://github.com/T5ive/Tools-Injector-Mod-Menu/files/6982367/Test-app.zip)
